version: "3.8"

services:
  mysql_server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

  tor_proxy:
    restart: always
    image: dperson/torproxy
    ports:
      - 9050:9050

  scraper:
    restart: always
    build: ./scraper
    ports:
      - 8080:8080
    volumes:
      - .:/scraper-volume
      - "/scraper-volume/node_modules"
    depends_on:
      - tor_proxy
      - mysql_server

  backend:
    restart: always
    build: ./backend
    ports:
      - 8090:8090
    volumes:
      - .:/backend-volume
      - "/backend-volume/node_modules"
    depends_on:
      - mysql_server

  client:
    restart: always
    build: ./client
    ports:
      - 80:80
    volumes:
      - .:/client-volume
      - "/client-volume/node_modules"
    depends_on:
      - backend
