version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - tor_proxy
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

  tor_proxy:
    image: dperson/torproxy
    ports:
      - 9050:9050
