version: "3.9"

services:
  mysql_server:
    restart: always
    image: mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  tor_proxy:
    restart: always
    image: dperson/torproxy
    ports:
      - 9050:9050

  ner_server:
    restart: always
    image: jgontrum/spacyapi:en_v2
    ports:
      - "127.0.0.1:9000:80"

  scraper:
    restart: always
    build: ./scraper
    ports:
      - 8080:8080
    volumes:
      - .:/scraper-volume
      - "/scraper-volume/node_modules"
    depends_on:
      - tor_proxy
      - mysql_server
      - ner_server
    environment:
      NODE_ENV: "${NODE_ENV}"

  backend:
    restart: always
    build: ./backend
    ports:
      - 8090:8090
    volumes:
      - .:/backend-volume
      - "/backend-volume/node_modules"
    depends_on:
      - mysql_server
    environment:
      NODE_ENV: "${NODE_ENV}"

  client:
    restart: always
    build: ./client
    ports:
      - 80:80
    volumes:
      - .:/client-volume
      - "/client-volume/node_modules"
    depends_on:
      - backend
